# Tensor

In [20]:
# importing modules
import torch
import numpy as np

## 1 . Directly from the data

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)
print(type(data))
print(type(x_data))


tensor([[1, 2],
        [3, 4]])
<class 'list'>
<class 'torch.Tensor'>


## 2 . From numpy array

In [5]:
data1 = [[5,6],[7,8]]
print(data1)
print(type(data1))
np_array = np.array(data1)
print(np_array)
print(type(np_array))
y_data = torch.from_numpy(np_array)
print(y_data)
print(type(y_data))

[[5, 6], [7, 8]]
<class 'list'>
[[5 6]
 [7 8]]
<class 'numpy.ndarray'>
tensor([[5, 6],
        [7, 8]], dtype=torch.int32)
<class 'torch.Tensor'>


## 3 . Tensor from another tensor

In [14]:
ones = torch.ones_like(y_data)
print(ones)
zeros = torch.zeros_like(ones)
print(zeros)
rn_val = torch.rand_like(zeros,dtype=float)
print(rn_val)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
tensor([[0, 0],
        [0, 0]], dtype=torch.int32)
tensor([[0.4499, 0.7220],
        [0.0729, 0.1426]], dtype=torch.float64)


## Shape= ( ) is tuple of tensor dimensions
## with constant or random tensors for given shape

In [32]:
shape=(3,4)
shapes = (3,4,)
r_ten = torch.rand(shape)
print(r_ten)
r_tens = torch.rand(shapes)
print(r_tens)
o_ten = torch.ones(shape)
print(o_ten)
o_tens = torch.ones(shapes)
print(o_tens)
z_ten = torch.zeros(shape)
print(z_ten)
z_tens = torch.ones(shapes)
print(o_tens)


tensor([[0.7761, 0.4138, 0.7400, 0.7916],
        [0.6012, 0.5045, 0.2411, 0.6847],
        [0.9032, 0.1752, 0.8685, 0.6322]])
tensor([[0.1916, 0.8451, 0.0813, 0.1175],
        [0.7424, 0.3283, 0.2717, 0.3233],
        [0.4424, 0.1902, 0.7840, 0.6253]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


## Attributes of a tensor

In [39]:
new_tensor = torch.rand(3,4)
print(new_tensor)
print(new_tensor.shape)
print(new_tensor.dtype)
print(new_tensor.device)

tensor([[0.7985, 0.3446, 0.4728, 0.5019],
        [0.4859, 0.5316, 0.2132, 0.3392],
        [0.7846, 0.5418, 0.6688, 0.3569]])
torch.Size([3, 4])
torch.float32
cpu


## Operations on tensors